# Generated by Django 3.2.3 on 2021-05-31 17:43

from django.db import migrations, models
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('alt', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Main Page Images',
                'verbose_name_plural': 'Main Page Images',
            },
        ),
        migrations.CreateModel(
            name='ParallaxImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parallax_image', models.ImageField(upload_to='images/')),
                ('parallax_image_alt', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Parallax Images',
                'verbose_name_plural': 'Parallax Images',
            },
        ),
        migrations.CreateModel(
            name='PhotosPageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('alt', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Photos Page Images',
                'verbose_name_plural': 'Photos Page Images',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('content', tinymce.models.HTMLField()),
                ('post_image', models.ImageField(upload_to='images/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
