# Generated by Django 3.2.3 on 2021-06-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20210602_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('image1', models.ImageField(upload_to='images/')),
                ('alt1', models.CharField(max_length=50)),
                ('image2', models.ImageField(upload_to='images/')),
                ('alt2', models.CharField(max_length=50)),
                ('image3', models.ImageField(upload_to='images/')),
                ('alt3', models.CharField(max_length=50)),
                ('image4', models.ImageField(upload_to='images/')),
                ('alt4', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
