# Generated by Django 3.2.3 on 2021-06-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainPageImages',
        ),
        migrations.DeleteModel(
            name='PhotosPageImages',
        ),
    ]
